- name: catalogue configure
  hosts: catalogue
  become: yes

  tasks:
  - name: enable node js 20
    ansible.builtin.command:  dnf module enable nodejs:20 -y

  - name: install node js
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create system user
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "roboshop system user"

  - name: delete app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete catalogue file
    ansible.builtin.file:
    path: /tmp/catalogue.zip
    state: absent

  - name: download catalogue file
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip

  - name: unarchive catalogue
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app 
      remote_src: yes
  
  - name: install dependeinces
    community.general.npm:
     path: /app

  - name: copy catalogue service
    ansible.builtin.copy:
     src: catalogue.service
     dest:  /etc/systemd/system/catalogue.service

  - name: copy mongo repo
    ansible.builtin.copy:
     src: mongo.repo
     dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.dnf:
     name: mongodb-mongosh
     state: present

  - name: check products loaded
    ansible.builtin.command: mongosh --host "{{MONGODB_HOST}}" -- quiet --eval 'db.getMongo()'.getDBNames().indexOf("catalogue")
    register: catalogue_output

  - name: print the output
    ansible.builtin.debug:
     msg: "{catalogue_output}"

  - name: load the products
    ansible.builtin.shell: mongosh --host "{{MONGODB_HOST}}" </app/db/master-data.js
    when: catalogue_output.stdout | int< 0

  - name: start catalogue
    ansible.builtin.service:
     name: catalogue
     state: restarted
     enable: yes


     

   




  





      


     


