- name: create ec2 and r53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-0cb476fa0ae55052d
    ami_id: ami-0220d79f3f480ecf5
    env: dev
    domain_name: devsecops2026.online
    action: create
    instances:
    - mongodb
    - catalogue
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: "t3.micro"
      security_group: "{{sg_id}}"
      image_id: "{{ami_id}}"
      name: "{{item}}-{{env}}"
      tags: 
        Project: roboshop
        Component: "{{item}}"
        Env: "{{env}}"
        name: "{{item}}"
    loop: "{{instances}}"
    register: ec2_output
    when: action == "create"

  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ec2_output}}"
    when: action == "create"


  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{domain_name}}"
      record: "{{ item.item }}-{{env}}.{{domain_name}}" #mongodb-dev.devsecops2026.online #frontend-dev.devsecops2026.online
      type: A 
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
    loop: "{{ ec2_output.results }}"
    when: action == "create"

  
  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{domain_name}}"
      record: "roboshop-{{env}}.{{domain_name}}" #roboshop-dev.devsecops2026.online 
      type: A 
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
    loop: "{{ ec2_output.results }}"
    when: 
    - item.item == "frontend"
    - action == "create"

  - name: delete r53 records
    amazon.aws.route53:
      state: absent
      zone: "{{domain_name}}"
      record: "{{item}}-{{env}}.{{domain_name}}" #roboshop-dev.devsecops2026.online 
      type: A 
      ttl: 1
    loop: "{{instances}}"
    when: action == "destroy"

  - name: delete instance
    amazon.aws.ec2_instance:
      state: absent
      name: "{{item}}-{{env}}"
    loop: "{{ instances}}"
    when: action == "destroy"


